<a href="https://colab.research.google.com/github/srijonpal/Sudoku_and_TicTacToe/blob/main/sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np
import random 

In [22]:
board = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,0,1,9,0,0,5],
        [0,0,0,0,0,0,0,0,0]]

In [23]:
def possible(row, column, number):
    global board
    #Is the number appearing in the given row?
    for i in range(0,9):
        if board[row][i] == number:
            return False

    #Is the number appearing in the given column?
    for i in range(0,9):
        if board[i][column] == number:
            return False
    
    #Is the number appearing in the given square?
    x0 = (column // 3) * 3
    y0 = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if board[y0+i][x0+j] == number:
                return False

    return True



In [24]:
def solve():
    global grid
    for row in range(0,9):
        for column in range(0,9):
            if board[row][column] == 0:
                for number in range(1,10):
                    if possible(row, column, number):
                        board[row][column] = number
                        solve()
                        board[row][column] = 0

                return


    print(np.matrix(board))
    input('More possible solutions')

In [26]:
solve()

[[5 3 4 2 8 6 1 7 9]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 7 4 5 6 2]
 [8 5 7 9 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [9 1 3 4 2 7 8 5 6]
 [3 6 1 5 4 9 2 8 7]
 [2 4 9 7 1 8 6 3 5]
 [7 8 5 6 3 2 9 1 4]]
More possible solutions
